# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'light.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("/*SCROLLVERTICAL*/\n"
"QScrollBar:vertical {\n"
"    border: 6px solid rgb(0, 0, 0, 0);\n"
"    margin: 14px 0px 14px 0px;\n"
"    width: 16px;\n"
"}\n"
"\n"
"QScrollBar:vertical:hover {\n"
"    border: 5px solid rgb(0, 0, 0, 0);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(0, 0, 0, 110);\n"
"    border-radius: 2px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    image: url(:/icon/ScrollTop.png);\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    image: url(:/icon/ScrollTopHover.png);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    image: url(:/icon/ScrollTopPressed.png);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    image: url(:/icon/ScrollBottom.png);\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {\n"
"    image: url(:/icon/ScrollBottomHover.png);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:pressed {\n"
"    image: url(:/icon/ScrollBottomPressed.png);\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/*SCROLLHORIZONTAL*/\n"
"QScrollBar:horizontal {\n"
"    border: 6px solid rgb(0, 0, 0, 0);\n"
"    margin: 0px 14px 0px 14px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QScrollBar:horizontal:hover {\n"
"    border: 5px solid rgb(0, 0, 0, 0);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(0, 0, 0, 110);\n"
"    border-radius: 2px;\n"
"    min-width: 25px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    image: url(:/icon/ScrollLeft.png);\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    image: url(:/icon/ScrollLeftHover.png);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"    image: url(:/icon/ScrollLeftPressed.png);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    image: url(:/icon/ScrollRight.png);\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover {\n"
"    image: url(:/icon/ScrollRightHover.png);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"    image: url(:/icon/ScrollRightPressed.png);\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/*LISTWIDGET*/\n"
"QListView {\n"
"    background-color: transparent;\n"
"    border: 1.5px solid rgb(0, 0, 0, 13);\n"
"    border-radius: 5px;\n"
"    outline: 0;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QListView::item {\n"
"    padding: 7px;\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(0, 0, 0, 7);\n"
"    border-radius: 5px;\n"
"    margin-bottom: 3px;\n"
"    padding-left: 0px;\n"
"}\n"
"\n"
"QListView::item:!selected:hover {\n"
"    background-color: rgb(0, 0, 0, 13);\n"
"    border-radius: 5px;\n"
"    margin-bottom: 3px;\n"
"    padding-left: 0px;\n"
"}\n"
"\n"
"/*COMBOBOX*/\n"
"QComboBox {\n"
"    background-color: rgb(0, 0, 0, 7);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"    border-radius: 5px;\n"
"    padding-left: 10px;\n"
"    min-height: 38px;\n"
"    max-height: 38px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: rgb(0, 0, 0, 13);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"}\n"
"\n"
"QComboBox::pressed {\n"
"    border: 1px solid rgb(0, 0, 0, 10);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icon/ComboBox.png);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: transparent;\n"
"    min-width: 50px;\n"
"}\n"
"\n"
"QComboBox:disabled {\n"
"    color: rgb(0, 0, 0, 110);\n"
"    background-color: rgb(0, 0, 0, 13);\n"
"    border: 1px solid rgb(0, 0, 0, 5);\n"
"}\n"
"\n"
"QComboBox::down-arrow:disabled {\n"
"    image: url(:/icon/ComboBoxDisabled.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 60, 720))
        self.sidebar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sidebar.setStyleSheet("background-color: rgba(255, 255, 255, 216);")
        self.sidebar.setObjectName("sidebar")
        self.foldBtn = QtWidgets.QPushButton(self.sidebar)
        self.foldBtn.setGeometry(QtCore.QRect(10, 20, 40, 40))
        self.foldBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: transparent;\n"
"border-radius:31px;\n"
"border-image: url(:/icon/unfold.png)\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/icon/unfold_selected.png)\n"
"}")
        self.foldBtn.setText("")
        self.foldBtn.setObjectName("foldBtn")
        self.analyzeBtn = QtWidgets.QPushButton(self.sidebar)
        self.analyzeBtn.setGeometry(QtCore.QRect(10, 220, 40, 40))
        self.analyzeBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: transparent;\n"
"border-radius:31px;\n"
"border-image: url(:/icon/analyze.png)\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/icon/analyze_selected.png)\n"
"}")
        self.analyzeBtn.setText("")
        self.analyzeBtn.setObjectName("analyzeBtn")
        self.videoBtn = QtWidgets.QPushButton(self.sidebar)
        self.videoBtn.setGeometry(QtCore.QRect(10, 120, 40, 40))
        self.videoBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: transparent;\n"
"border-radius:31px;\n"
"border-image: url(:/icon/video.png)\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/icon/video_selected.png)\n"
"}")
        self.videoBtn.setText("")
        self.videoBtn.setObjectName("videoBtn")
        self.homeBtn = QtWidgets.QPushButton(self.sidebar)
        self.homeBtn.setGeometry(QtCore.QRect(10, 70, 40, 40))
        self.homeBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: transparent;\n"
"border-radius:31px;\n"
"border-image: url(:/icon/home.png)\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/icon/home_selected.png)\n"
"}")
        self.homeBtn.setText("")
        self.homeBtn.setObjectName("homeBtn")
        self.userBtn = QtWidgets.QPushButton(self.sidebar)
        self.userBtn.setGeometry(QtCore.QRect(10, 170, 40, 40))
        self.userBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: transparent;\n"
"border-radius:31px;\n"
"border-image: url(:/icon/user.png)\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/icon/user_selected.png)\n"
"}")
        self.userBtn.setText("")
        self.userBtn.setObjectName("userBtn")
        self.analyzeLabel = QtWidgets.QLabel(self.sidebar)
        self.analyzeLabel.setGeometry(QtCore.QRect(60, 220, 80, 40))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(10)
        font.setBold(False)
        self.analyzeLabel.setFont(font)
        self.analyzeLabel.setStyleSheet("background-color: transparent;")
        self.analyzeLabel.setObjectName("analyzeLabel")
        self.videoLabel = QtWidgets.QLabel(self.sidebar)
        self.videoLabel.setGeometry(QtCore.QRect(60, 120, 80, 40))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(10)
        font.setBold(False)
        self.videoLabel.setFont(font)
        self.videoLabel.setStyleSheet("background-color: transparent;")
        self.videoLabel.setObjectName("videoLabel")
        self.userLabel = QtWidgets.QLabel(self.sidebar)
        self.userLabel.setGeometry(QtCore.QRect(60, 170, 80, 40))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(10)
        font.setBold(False)
        self.userLabel.setFont(font)
        self.userLabel.setStyleSheet("background-color: transparent;")
        self.userLabel.setWordWrap(True)
        self.userLabel.setObjectName("userLabel")
        self.homeLabel = QtWidgets.QLabel(self.sidebar)
        self.homeLabel.setGeometry(QtCore.QRect(60, 70, 80, 40))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(10)
        font.setBold(False)
        self.homeLabel.setFont(font)
        self.homeLabel.setStyleSheet("background-color: transparent;")
        self.homeLabel.setObjectName("homeLabel")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(59, 0, 1221, 720))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.home = QtWidgets.QWidget(self.page_3)
        self.home.setGeometry(QtCore.QRect(0, 0, 1220, 720))
        self.home.setStyleSheet("background-color: transparent;")
        self.home.setObjectName("home")
        self.gridLayoutWidget = QtWidgets.QWidget(self.home)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1221, 721))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(40, 115, 40, 115)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(42)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.home)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1130, 630, 71, 74))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.refreshBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.refreshBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0, 7);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"    border-radius: 7px;\n"
"    min-height: 70px;\n"
"    max-height: 70px;\n"
"    border-image: url(:/icon/refresh.png)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 0, 0, 10);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    color: rgb(0, 0, 0, 150);\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    color: rgb(0, 0, 0, 110);\n"
"    background-color: rgb(0, 0, 0, 13);\n"
"    border: 1px solid rgb(0, 0, 0, 5);\n"
"}")
        self.refreshBtn.setText("")
        self.refreshBtn.setObjectName("refreshBtn")
        self.verticalLayout_5.addWidget(self.refreshBtn)
        self.home_label = QtWidgets.QLabel(self.home)
        self.home_label.setGeometry(QtCore.QRect(260, 10, 700, 95))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 65 Medium")
        font.setPointSize(12)
        self.home_label.setFont(font)
        self.home_label.setAlignment(QtCore.Qt.AlignCenter)
        self.home_label.setObjectName("home_label")
        self.user_comboBox = QtWidgets.QComboBox(self.home)
        self.user_comboBox.setGeometry(QtCore.QRect(980, 40, 150, 40))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(10)
        self.user_comboBox.setFont(font)
        self.user_comboBox.setObjectName("user_comboBox")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.video = QtWidgets.QWidget(self.page_4)
        self.video.setGeometry(QtCore.QRect(-1, 0, 1221, 720))
        self.video.setStyleSheet("background-color: transparent;")
        self.video.setObjectName("video")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.video)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 120, 1221, 601))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_video_main = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_video_main.setContentsMargins(40, 35, 40, 80)
        self.gridLayout_video_main.setHorizontalSpacing(20)
        self.gridLayout_video_main.setVerticalSpacing(42)
        self.gridLayout_video_main.setObjectName("gridLayout_video_main")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.video)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1221, 121))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_video_button = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_video_button.setContentsMargins(40, 20, 40, 0)
        self.gridLayout_video_button.setHorizontalSpacing(15)
        self.gridLayout_video_button.setVerticalSpacing(20)
        self.gridLayout_video_button.setObjectName("gridLayout_video_button")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.video)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(1140, 660, 41, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.refreshBtn_video = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.refreshBtn_video.setMinimumSize(QtCore.QSize(36, 38))
        self.refreshBtn_video.setMaximumSize(QtCore.QSize(36, 38))
        self.refreshBtn_video.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0, 7);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"    border-radius: 7px;\n"
"    min-height: 36px;\n"
"    max-height: 36px;\n"
"    border-image: url(:/icon/refresh.png)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 0, 0, 10);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    color: rgb(0, 0, 0, 150);\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    color: rgb(0, 0, 0, 110);\n"
"    background-color: rgb(0, 0, 0, 13);\n"
"    border: 1px solid rgb(0, 0, 0, 5);\n"
"}")
        self.refreshBtn_video.setText("")
        self.refreshBtn_video.setObjectName("refreshBtn_video")
        self.verticalLayout_7.addWidget(self.refreshBtn_video)
        self.predict_btn = QtWidgets.QPushButton(self.video)
        self.predict_btn.setGeometry(QtCore.QRect(820, 661, 300, 38))
        self.predict_btn.setMinimumSize(QtCore.QSize(36, 38))
        self.predict_btn.setMaximumSize(QtCore.QSize(300, 38))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(9)
        self.predict_btn.setFont(font)
        self.predict_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0, 7);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"    border-radius: 7px;\n"
"    min-height: 36px;\n"
"    max-height: 36px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 0, 0, 10);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    color: rgb(0, 0, 0, 150);\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    color: rgb(0, 0, 0, 110);\n"
"    background-color: rgb(0, 0, 0, 13);\n"
"    border: 1px solid rgb(0, 0, 0, 5);\n"
"}")
        self.predict_btn.setObjectName("predict_btn")
        self.stackedWidget.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.listView_user = QtWidgets.QListView(self.page)
        self.listView_user.setGeometry(QtCore.QRect(40, 70, 190, 600))
        self.listView_user.setObjectName("listView_user")
        self.listView_video = QtWidgets.QListView(self.page)
        self.listView_video.setGeometry(QtCore.QRect(300, 70, 600, 600))
        self.listView_video.setObjectName("listView_video")
        self.listView_similar = QtWidgets.QListView(self.page)
        self.listView_similar.setGeometry(QtCore.QRect(970, 70, 190, 600))
        self.listView_similar.setObjectName("listView_similar")
        self.user_label = QtWidgets.QLabel(self.page)
        self.user_label.setGeometry(QtCore.QRect(40, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 65 Medium")
        font.setPointSize(12)
        self.user_label.setFont(font)
        self.user_label.setAlignment(QtCore.Qt.AlignCenter)
        self.user_label.setObjectName("user_label")
        self.similar_label = QtWidgets.QLabel(self.page)
        self.similar_label.setGeometry(QtCore.QRect(970, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 65 Medium")
        font.setPointSize(12)
        self.similar_label.setFont(font)
        self.similar_label.setAlignment(QtCore.Qt.AlignCenter)
        self.similar_label.setObjectName("similar_label")
        self.video_label = QtWidgets.QLabel(self.page)
        self.video_label.setGeometry(QtCore.QRect(300, 20, 601, 41))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 65 Medium")
        font.setPointSize(12)
        self.video_label.setFont(font)
        self.video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_label.setObjectName("video_label")
        self.user_count_label = QtWidgets.QLabel(self.page)
        self.user_count_label.setGeometry(QtCore.QRect(40, 670, 191, 41))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(12)
        self.user_count_label.setFont(font)
        self.user_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.user_count_label.setObjectName("user_count_label")
        self.video_count_label = QtWidgets.QLabel(self.page)
        self.video_count_label.setGeometry(QtCore.QRect(300, 670, 601, 41))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(12)
        self.video_count_label.setFont(font)
        self.video_count_label.setText("")
        self.video_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_count_label.setObjectName("video_count_label")
        self.similar_count_label = QtWidgets.QLabel(self.page)
        self.similar_count_label.setGeometry(QtCore.QRect(970, 670, 191, 41))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(12)
        self.similar_count_label.setFont(font)
        self.similar_count_label.setText("")
        self.similar_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.similar_count_label.setObjectName("similar_count_label")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.listView_cluster_detail = QtWidgets.QListView(self.page_2)
        self.listView_cluster_detail.setGeometry(QtCore.QRect(380, 95, 700, 550))
        self.listView_cluster_detail.setObjectName("listView_cluster_detail")
        self.listView_cluster = QtWidgets.QListView(self.page_2)
        self.listView_cluster.setGeometry(QtCore.QRect(120, 95, 190, 550))
        self.listView_cluster.setObjectName("listView_cluster")
        self.video_cluster_btn = QtWidgets.QPushButton(self.page_2)
        self.video_cluster_btn.setGeometry(QtCore.QRect(340, 20, 201, 50))
        self.video_cluster_btn.setMinimumSize(QtCore.QSize(36, 38))
        self.video_cluster_btn.setMaximumSize(QtCore.QSize(300, 52))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(10)
        self.video_cluster_btn.setFont(font)
        self.video_cluster_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0, 7);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"    border-radius: 7px;\n"
"    min-height: 36px;\n"
"    max-height: 50px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 0, 0, 10);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    color: rgb(0, 0, 0, 150);\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    color: rgb(0, 0, 0, 110);\n"
"    background-color: rgb(0, 0, 0, 13);\n"
"    border: 1px solid rgb(0, 0, 0, 5);\n"
"}")
        self.video_cluster_btn.setObjectName("video_cluster_btn")
        self.user_cluster_btn = QtWidgets.QPushButton(self.page_2)
        self.user_cluster_btn.setGeometry(QtCore.QRect(680, 20, 201, 50))
        self.user_cluster_btn.setMinimumSize(QtCore.QSize(36, 38))
        self.user_cluster_btn.setMaximumSize(QtCore.QSize(300, 52))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(10)
        self.user_cluster_btn.setFont(font)
        self.user_cluster_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0, 7);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"    border-radius: 7px;\n"
"    min-height: 36px;\n"
"    max-height: 50px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 0, 0, 10);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    color: rgb(0, 0, 0, 150);\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    color: rgb(0, 0, 0, 110);\n"
"    background-color: rgb(0, 0, 0, 13);\n"
"    border: 1px solid rgb(0, 0, 0, 5);\n"
"}")
        self.user_cluster_btn.setObjectName("user_cluster_btn")
        self.stackedWidget.addWidget(self.page_2)
        self.stackedWidget.raise_()
        self.sidebar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.foldBtn.clicked.connect(MainWindow.onExpandClicked) # type: ignore
        self.refreshBtn.clicked.connect(MainWindow.home_init) # type: ignore
        self.homeBtn.clicked.connect(MainWindow.home_show) # type: ignore
        self.videoBtn.clicked.connect(MainWindow.video_show) # type: ignore
        self.userBtn.clicked.connect(MainWindow.user_show) # type: ignore
        self.analyzeBtn.clicked.connect(MainWindow.analyze_show) # type: ignore
        self.predict_btn.clicked.connect(MainWindow.predict_video) # type: ignore
        self.video_cluster_btn.clicked.connect(MainWindow.video_cluster) # type: ignore
        self.user_cluster_btn.clicked.connect(MainWindow.user_cluster) # type: ignore
        self.refreshBtn_video.clicked.connect(MainWindow.refresh_video_btn_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "短视频推荐系统"))
        self.analyzeLabel.setText(_translate("MainWindow", "聚类分析"))
        self.videoLabel.setText(_translate("MainWindow", "视频总览"))
        self.userLabel.setText(_translate("MainWindow", "用户总览"))
        self.homeLabel.setText(_translate("MainWindow", "首页"))
        self.home_label.setText(_translate("MainWindow", "TextLabel"))
        self.predict_btn.setText(_translate("MainWindow", "热度变化预测"))
        self.user_label.setText(_translate("MainWindow", "用户列表"))
        self.similar_label.setText(_translate("MainWindow", "相似用户"))
        self.video_label.setText(_translate("MainWindow", "用户观看视频列表"))
        self.user_count_label.setText(_translate("MainWindow", "用户总数：10000"))
        self.video_cluster_btn.setText(_translate("MainWindow", "视频聚类分析"))
        self.user_cluster_btn.setText(_translate("MainWindow", "用户聚类分析"))
import resources_rc
