# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'light.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.home = QtWidgets.QWidget(self.centralwidget)
        self.home.setGeometry(QtCore.QRect(60, 0, 1220, 720))
        self.home.setStyleSheet("background-color: transparent;")
        self.home.setObjectName("home")
        self.gridLayoutWidget = QtWidgets.QWidget(self.home)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1221, 721))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(40, 115, 40, 115)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(42)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.home)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1130, 630, 71, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.refreshBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.refreshBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0, 7);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"    border-radius: 7px;\n"
"    min-height: 70px;\n"
"    max-height: 70px;\n"
"    border-image: url(:/icon/refresh.png)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 0, 0, 10);\n"
"    border: 1px solid rgb(0, 0, 0, 13);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    color: rgb(0, 0, 0, 150);\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    color: rgb(0, 0, 0, 110);\n"
"    background-color: rgb(0, 0, 0, 13);\n"
"    border: 1px solid rgb(0, 0, 0, 5);\n"
"}")
        self.refreshBtn.setText("")
        self.refreshBtn.setObjectName("refreshBtn")
        self.verticalLayout_5.addWidget(self.refreshBtn)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 141, 721))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.sidebar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sidebar.setStyleSheet("background-color: rgba(255, 255, 255, 216);")
        self.sidebar.setObjectName("sidebar")
        self.foldBtn = QtWidgets.QPushButton(self.sidebar)
        self.foldBtn.setGeometry(QtCore.QRect(10, 20, 40, 40))
        self.foldBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: transparent;\n"
"border-radius:31px;\n"
"border-image: url(:/icon/unfold.png)\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/icon/unfold_selected.png)\n"
"}")
        self.foldBtn.setText("")
        self.foldBtn.setObjectName("foldBtn")
        self.searchBtn = QtWidgets.QPushButton(self.sidebar)
        self.searchBtn.setGeometry(QtCore.QRect(10, 120, 40, 40))
        self.searchBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: transparent;\n"
"border-radius:31px;\n"
"border-image: url(:/icon/search.png)\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/icon/search_selected.png)\n"
"}")
        self.searchBtn.setText("")
        self.searchBtn.setObjectName("searchBtn")
        self.videoBtn = QtWidgets.QPushButton(self.sidebar)
        self.videoBtn.setGeometry(QtCore.QRect(10, 170, 40, 40))
        self.videoBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: transparent;\n"
"border-radius:31px;\n"
"border-image: url(:/icon/video.png)\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/icon/video_selected.png)\n"
"}")
        self.videoBtn.setText("")
        self.videoBtn.setObjectName("videoBtn")
        self.homeBtn = QtWidgets.QPushButton(self.sidebar)
        self.homeBtn.setGeometry(QtCore.QRect(10, 70, 40, 40))
        self.homeBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: transparent;\n"
"border-radius:31px;\n"
"border-image: url(:/icon/home.png)\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/icon/home_selected.png)\n"
"}")
        self.homeBtn.setText("")
        self.homeBtn.setObjectName("homeBtn")
        self.userBtn = QtWidgets.QPushButton(self.sidebar)
        self.userBtn.setGeometry(QtCore.QRect(10, 220, 40, 40))
        self.userBtn.setStyleSheet("QPushButton\n"
"{\n"
"background-color: transparent;\n"
"border-radius:31px;\n"
"border-image: url(:/icon/user.png)\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/icon/user_selected.png)\n"
"}")
        self.userBtn.setText("")
        self.userBtn.setObjectName("userBtn")
        self.searchLabel = QtWidgets.QLabel(self.sidebar)
        self.searchLabel.setGeometry(QtCore.QRect(60, 120, 80, 40))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(10)
        font.setBold(False)
        self.searchLabel.setFont(font)
        self.searchLabel.setObjectName("searchLabel")
        self.videoLabel = QtWidgets.QLabel(self.sidebar)
        self.videoLabel.setGeometry(QtCore.QRect(60, 170, 80, 40))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(10)
        font.setBold(False)
        self.videoLabel.setFont(font)
        self.videoLabel.setObjectName("videoLabel")
        self.userLabel = QtWidgets.QLabel(self.sidebar)
        self.userLabel.setGeometry(QtCore.QRect(60, 220, 80, 40))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(10)
        font.setBold(False)
        self.userLabel.setFont(font)
        self.userLabel.setObjectName("userLabel")
        self.homeLabel = QtWidgets.QLabel(self.sidebar)
        self.homeLabel.setGeometry(QtCore.QRect(60, 70, 80, 40))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(10)
        font.setBold(False)
        self.homeLabel.setFont(font)
        self.homeLabel.setObjectName("homeLabel")
        self.horizontalLayout.addWidget(self.sidebar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.foldBtn.clicked.connect(MainWindow.onExpandClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "短视频推荐系统"))
        self.searchLabel.setText(_translate("MainWindow", "搜索"))
        self.videoLabel.setText(_translate("MainWindow", "视频总览"))
        self.userLabel.setText(_translate("MainWindow", "用户总览"))
        self.homeLabel.setText(_translate("MainWindow", "首页"))
import resources_rc
